name: Count Lines of Code against folder

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the main branch
on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Calculate Lines of Code
        id: loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.5
        with:
          directory: "./jenkinsfiles " #Optional #Comma Seperated
          include_ext: "ts,js,txt"                      #Optional # Comma Seperated
          
      # Publish Lines of Code Summary  # Optional
      - name: Add Lines of Code Summary
        run: echo "${{ steps.loc.outputs.lines-of-code-summary }}" >> $GITHUB_STEP_SUMMARY

      - name: print output # Optional
        shell: pwsh
        run: | 
          Write-Host 'Total Lines of Code...:  ${{ steps.loc.outputs.total_lines }}'
          Write-Host 'Lines of Code Markdown Report Path...:  ${{ steps.loc.outputs.loc_report }}' 
