name: Count Lines of Code

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the main branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Calculate Lines of Code
        id: loc
        uses: PavanMudigonda/lines-of-code-reporter@v1.5   
        with:
          directory: "src"                          #Optional #Comma Seperated
          include_lang: "JavaScript,TypeScript"     #Optional # Comma Seperated
          #exclude_lang: "PowerShell,Shell,Go"       #Optional # Comma Seperated
          #exclude_dir: ".github"                    #Optional # Comma Seperated

      # Publish Lines of Code Summary  # Optional
      - name: Add Lines of Code Summary
        run: echo "${{ steps.loc.outputs.lines-of-code-summary }}" >> $GITHUB_STEP_SUMMARY

      - name: print output # Optional
        shell: pwsh
        run: | 
          Write-Host 'Total Lines of Code...:  ${{ steps.loc.outputs.total_lines }}'
          Write-Host 'Lines of Code Markdown Report Path...:  ${{ steps.loc.outputs.loc_report }}' 
