---
name: nightly
on:
  workflow_dispatch:
  
jobs:
  nightly:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: nightly/***

